using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class LinkP2_Model 
{
    [RealtimeProperty(31, true, true)] bool _linkP2Active;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class LinkP2_Model : RealtimeModel {
    public bool linkP2Active {
        get {
            return _linkP2ActiveProperty.value;
        }
        set {
            if (_linkP2ActiveProperty.value == value) return;
            _linkP2ActiveProperty.value = value;
            InvalidateReliableLength();
            FireLinkP2ActiveDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(LinkP2_Model model, T value);
    public event PropertyChangedHandler<bool> linkP2ActiveDidChange;
    
    public enum PropertyID : uint {
        LinkP2Active = 31,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _linkP2ActiveProperty;
    
    #endregion
    
    public LinkP2_Model() : base(null) {
        _linkP2ActiveProperty = new ReliableProperty<bool>(31, _linkP2Active);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _linkP2ActiveProperty.UnsubscribeCallback();
    }
    
    private void FireLinkP2ActiveDidChange(bool value) {
        try {
            linkP2ActiveDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _linkP2ActiveProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _linkP2ActiveProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.LinkP2Active: {
                    changed = _linkP2ActiveProperty.Read(stream, context);
                    if (changed) FireLinkP2ActiveDidChange(linkP2Active);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _linkP2Active = linkP2Active;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
