using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class FirstButtonModel 
{
    [RealtimeProperty(50, true, true)] bool _startClicked;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class FirstButtonModel : RealtimeModel {
    public bool startClicked {
        get {
            return _startClickedProperty.value;
        }
        set {
            if (_startClickedProperty.value == value) return;
            _startClickedProperty.value = value;
            InvalidateReliableLength();
            FireStartClickedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(FirstButtonModel model, T value);
    public event PropertyChangedHandler<bool> startClickedDidChange;
    
    public enum PropertyID : uint {
        StartClicked = 50,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _startClickedProperty;
    
    #endregion
    
    public FirstButtonModel() : base(null) {
        _startClickedProperty = new ReliableProperty<bool>(50, _startClicked);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _startClickedProperty.UnsubscribeCallback();
    }
    
    private void FireStartClickedDidChange(bool value) {
        try {
            startClickedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _startClickedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _startClickedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.StartClicked: {
                    changed = _startClickedProperty.Read(stream, context);
                    if (changed) FireStartClickedDidChange(startClicked);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _startClicked = startClicked;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
