using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;


[RealtimeModel]
public partial class Led_Room2_Model 
{
    [RealtimeProperty(6,false,true)] Color _ledP2Colors ;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Led_Room2_Model : RealtimeModel {
    public UnityEngine.Color ledP2Colors {
        get {
            return _ledP2ColorsProperty.value;
        }
        set {
            if (_ledP2ColorsProperty.value == value) return;
            _ledP2ColorsProperty.value = value;
            InvalidateUnreliableLength();
            FireLedP2ColorsDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(Led_Room2_Model model, T value);
    public event PropertyChangedHandler<UnityEngine.Color> ledP2ColorsDidChange;
    
    public enum PropertyID : uint {
        LedP2Colors = 6,
    }
    
    #region Properties
    
    private UnreliableProperty<UnityEngine.Color> _ledP2ColorsProperty;
    
    #endregion
    
    public Led_Room2_Model() : base(null) {
        _ledP2ColorsProperty = new UnreliableProperty<UnityEngine.Color>(6, _ledP2Colors);
    }
    
    private void FireLedP2ColorsDidChange(UnityEngine.Color value) {
        try {
            ledP2ColorsDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _ledP2ColorsProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _ledP2ColorsProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.LedP2Colors: {
                    changed = _ledP2ColorsProperty.Read(stream, context);
                    if (changed) FireLedP2ColorsDidChange(ledP2Colors);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _ledP2Colors = ledP2Colors;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
