using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;
[RealtimeModel] public partial class Roof_Model
{
    [RealtimeProperty(9, true, true)] bool _roofEnabled;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Roof_Model : RealtimeModel {
    public bool roofEnabled {
        get {
            return _roofEnabledProperty.value;
        }
        set {
            if (_roofEnabledProperty.value == value) return;
            _roofEnabledProperty.value = value;
            InvalidateReliableLength();
            FireRoofEnabledDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(Roof_Model model, T value);
    public event PropertyChangedHandler<bool> roofEnabledDidChange;
    
    public enum PropertyID : uint {
        RoofEnabled = 9,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _roofEnabledProperty;
    
    #endregion
    
    public Roof_Model() : base(null) {
        _roofEnabledProperty = new ReliableProperty<bool>(9, _roofEnabled);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _roofEnabledProperty.UnsubscribeCallback();
    }
    
    private void FireRoofEnabledDidChange(bool value) {
        try {
            roofEnabledDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _roofEnabledProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _roofEnabledProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.RoofEnabled: {
                    changed = _roofEnabledProperty.Read(stream, context);
                    if (changed) FireRoofEnabledDidChange(roofEnabled);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _roofEnabled = roofEnabled;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
